// <auto-generated />
using System;
using DataReceiver.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataReceiver.Shared.Database.Migrations
{
    [DbContext(typeof(DataReceiverContext))]
    partial class DataReceiverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataReceiver.Shared.Database.Combination", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("combination_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("investment_number")
                        .HasColumnType("bigint");

                    b.Property<decimal>("liability")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("odds")
                        .HasColumnType("decimal(6,2)");

                    b.Property<long>("odds_number")
                        .HasColumnType("bigint");

                    b.Property<int>("pool_id")
                        .HasColumnType("int");

                    b.Property<decimal>("sales")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.HasIndex(new[] { "pool_id", "combination_id" }, "combination_with_pool_id");

                    b.ToTable("combination");
                });

            modelBuilder.Entity("DataReceiver.Shared.Database.Pool", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("game_id")
                        .HasColumnType("int");

                    b.Property<string>("instance_name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("pool");
                });
#pragma warning restore 612, 618
        }
    }
}
